export type Category = "Coils & Pods" | "Devices" | "Disposables" | "E-liquids" | "Nic Pouches";

export type Product = {
  slug: string;
  name: string;
  brand: string;
  category: Category;
  price: number;
  compareAt?: number;
  puffCount?: string;
  flavour?: string;
  image: string;
  inStock: boolean;
};

export const CATEGORIES: Category[] = [
  "Coils & Pods",
  "Devices",
  "Disposables",
  "E-liquids",
  "Nic Pouches",
];

export const products: Product[] = [
  {
    slug: "oxva-xlim-go-lite-device-kit",
    name: "Xlim Go Lite Device Kit",
    brand: "OXVA",
    category: "Devices",
    price: 700,
    compareAt: 760,
    image: "/products/oxva-xlim-go-lite-device-kit.jpg",
    inStock: true,
  },
  {
    slug: "smok-arco-digi-device-kit",
    name: "Arco Digi Device Kit",
    brand: "Smok",
    category: "Devices",
    price: 380,
    image: "/products/smok-arco-digi-device-kit.jpg",
    inStock: true,
  },
  {
    slug: "vaporesso-vibe-se-device-kit",
    name: "Vibe SE Device Kit",
    brand: "Vaporesso",
    category: "Devices",
    price: 640,
    compareAt: 720,
    image: "/products/vaporesso-vibe-se-device-kit.jpg",
    inStock: false,
  },
  {
    slug: "vaporesso-xros-6-device-kit",
    name: "Xros 6 Device Kit",
    brand: "Vaporesso",
    category: "Devices",
    price: 350,
    compareAt: 450,
    image: "/products/vaporesso-xros-6-device-kit.jpg",
    inStock: true,
  },
  {
    slug: "oxva-nexlim-0-6-ohm-4ml-pod",
    name: "Nexlim 0.6 Ohm 4ml Pod",
    brand: "OXVA",
    category: "Coils & Pods",
    price: 125,
    compareAt: 225,
    image: "/products/oxva-nexlim-0-6-ohm-4ml-pod.jpg",
    inStock: true,
  },
  {
    slug: "oxva-nexlim-0-8-ohm-4ml-pod",
    name: "Nexlim 0.8 Ohm 4ml Pod",
    brand: "OXVA",
    category: "Coils & Pods",
    price: 115,
    image: "/products/oxva-nexlim-0-8-ohm-4ml-pod.jpg",
    inStock: true,
  },
  {
    slug: "oxva-xlim-0-6-ohm-3ml-pod",
    name: "Xlim 0.6 Ohm 3ml Pod",
    brand: "OXVA",
    category: "Coils & Pods",
    price: 45,
    image: "/products/oxva-xlim-0-6-ohm-3ml-pod.jpg",
    inStock: true,
  },
  {
    slug: "oxva-xlim-1-2-ohm-3ml-pod",
    name: "Xlim 1.2 Ohm 3ml Pod",
    brand: "OXVA",
    category: "Coils & Pods",
    price: 105,
    image: "/products/oxva-xlim-1-2-ohm-3ml-pod.jpg",
    inStock: true,
  },
  {
    slug: "smok-arco-pod-0-4-ohm-3ml",
    name: "Arco Pod 0.4 Ohm 3ml",
    brand: "Smok",
    category: "Coils & Pods",
    price: 95,
    compareAt: 175,
    image: "/products/smok-arco-pod-0-4-ohm-3ml.jpg",
    inStock: true,
  },
  {
    slug: "smok-arco-pod-0-8-ohm-3ml",
    name: "Arco Pod 0.8 Ohm 3ml",
    brand: "Smok",
    category: "Coils & Pods",
    price: 95,
    image: "/products/smok-arco-pod-0-8-ohm-3ml.jpg",
    inStock: true,
  },
  {
    slug: "smok-novo-pod-0-8-ohm-3ml",
    name: "Novo Pod 0.8 Ohm 3ml",
    brand: "Smok",
    category: "Coils & Pods",
    price: 155,
    image: "/products/smok-novo-pod-0-8-ohm-3ml.jpg",
    inStock: true,
  },
  {
    slug: "uwell-caliburn-gpp-0-9-ohm-3ml-pod",
    name: "Caliburn GPP 0.9 Ohm 3ml Pod",
    brand: "Uwell",
    category: "Coils & Pods",
    price: 105,
    compareAt: 165,
    image: "/products/uwell-caliburn-gpp-0-9-ohm-3ml-pod.jpg",
    inStock: true,
  },
  {
    slug: "vaporesso-xros-corex-0-6-ohm-3ml-pod",
    name: "Xros Corex 0.6 Ohm 3ml Pod",
    brand: "Vaporesso",
    category: "Coils & Pods",
    price: 135,
    image: "/products/vaporesso-xros-corex-0-6-ohm-3ml-pod.jpg",
    inStock: true,
  },
  {
    slug: "vaporesso-xros-corex-0-8-ohm-3ml-pod",
    name: "Xros Corex 0.8 Ohm 3ml Pod",
    brand: "Vaporesso",
    category: "Coils & Pods",
    price: 75,
    image: "/products/vaporesso-xros-corex-0-8-ohm-3ml-pod.jpg",
    inStock: false,
  },
  {
    slug: "siberia-red-dry-nic-pouches-43mg",
    name: "Red Dry Nic Pouches 43mg",
    brand: "Siberia",
    category: "Nic Pouches",
    price: 90,
    image: "/products/siberia-red-dry-nic-pouches-43mg.jpg",
    inStock: true,
  },
  {
    slug: "velo-icy-berries-10mg-nic-pouches",
    name: "Icy Berries 10mg Nic Pouches",
    brand: "VELO",
    category: "Nic Pouches",
    price: 90,
    image: "/products/velo-icy-berries-10mg-nic-pouches.jpg",
    inStock: true,
  },
  {
    slug: "velo-mclaren-sweet-papaya-8mg-nic-pouches",
    name: "McLaren Sweet Papaya 8mg Nic Pouches",
    brand: "VELO",
    category: "Nic Pouches",
    price: 130,
    image: "/products/velo-mclaren-sweet-papaya-8mg-nic-pouches.jpg",
    inStock: true,
  },
  {
    slug: "velo-wintry-watermelon-10mg-nic-pouches",
    name: "Wintry Watermelon 10mg Nic Pouches",
    brand: "VELO",
    category: "Nic Pouches",
    price: 110,
    image: "/products/velo-wintry-watermelon-10mg-nic-pouches.jpg",
    inStock: true,
  },
  {
    slug: "artery-cs5-25k-blueberry-cherry-cranberry",
    name: "Cs5 25K - Blueberry Cherry Cranberry",
    brand: "Artery",
    category: "Disposables",
    price: 130,
    flavour: "Blueberry Cherry Cranberry",
    image: "/products/artery-cs5-25k-blueberry-cherry-cranberry.jpg",
    inStock: true,
  },
  {
    slug: "artery-cs5-25k-blue-razz",
    name: "Cs5 25K - Blue Razz",
    brand: "Artery",
    category: "Disposables",
    price: 240,
    compareAt: 320,
    flavour: "Blue Razz",
    image: "/products/artery-cs5-25k-blue-razz.jpg",
    inStock: true,
  },
  {
    slug: "artery-cs5-25k-cotton-candy",
    name: "Cs5 25K - Cotton Candy",
    brand: "Artery",
    category: "Disposables",
    price: 440,
    compareAt: 510,
    flavour: "Cotton Candy",
    image: "/products/artery-cs5-25k-cotton-candy.jpg",
    inStock: true,
  },
  {
    slug: "artery-cs5-25k-miami-mint",
    name: "Cs5 25K - Miami Mint",
    brand: "Artery",
    category: "Disposables",
    price: 120,
    compareAt: 140,
    flavour: "Miami Mint",
    image: "/products/artery-cs5-25k-miami-mint.jpg",
    inStock: true,
  },
  {
    slug: "bewolk-x-jack-parrow-10k-bubblegum-melkie",
    name: "10K - Bubblegum Melkie",
    brand: "Bewolk x Jack Parrow",
    category: "Disposables",
    price: 340,
    flavour: "Bubblegum Melkie",
    image: "/products/bewolk-x-jack-parrow-10k-bubblegum-melkie.jpg",
    inStock: true,
  },
  {
    slug: "bewolk-x-jack-parrow-10k-cherry-sucker",
    name: "10K - Cherry Sucker",
    brand: "Bewolk x Jack Parrow",
    category: "Disposables",
    price: 450,
    flavour: "Cherry Sucker",
    image: "/products/bewolk-x-jack-parrow-10k-cherry-sucker.jpg",
    inStock: true,
  },
  {
    slug: "bewolk-x-jack-parrow-10k-grape-pop",
    name: "10K - Grape Pop",
    brand: "Bewolk x Jack Parrow",
    category: "Disposables",
    price: 400,
    flavour: "Grape Pop",
    image: "/products/bewolk-x-jack-parrow-10k-grape-pop.jpg",
    inStock: true,
  },
  {
    slug: "bewolk-x-jack-parrow-10k-j-bomb",
    name: "10K - J Bomb",
    brand: "Bewolk x Jack Parrow",
    category: "Disposables",
    price: 380,
    compareAt: 420,
    flavour: "J Bomb",
    image: "/products/bewolk-x-jack-parrow-10k-j-bomb.jpg",
    inStock: true,
  },
  {
    slug: "bewolk-x-jack-parrow-10k-red-mamba-slush",
    name: "10K - Red Mamba Slush",
    brand: "Bewolk x Jack Parrow",
    category: "Disposables",
    price: 440,
    flavour: "Red Mamba Slush",
    image: "/products/bewolk-x-jack-parrow-10k-red-mamba-slush.jpg",
    inStock: true,
  },
  {
    slug: "elfbar-ew18k-pod-berry-grape",
    name: "EW18K Pod - Berry Grape",
    brand: "Elfbar",
    category: "Disposables",
    price: 360,
    flavour: "Berry Grape",
    image: "/products/elfbar-ew18k-pod-berry-grape.jpg",
    inStock: true,
  },
  {
    slug: "elfbar-ew18k-pod-california-cherry",
    name: "EW18K Pod - California Cherry",
    brand: "Elfbar",
    category: "Disposables",
    price: 230,
    flavour: "California Cherry",
    image: "/products/elfbar-ew18k-pod-california-cherry.jpg",
    inStock: true,
  },
  {
    slug: "elfbar-ew18k-pod-cotton-candy-ice",
    name: "EW18K Pod - Cotton Candy Ice",
    brand: "Elfbar",
    category: "Disposables",
    price: 400,
    compareAt: 420,
    flavour: "Cotton Candy Ice",
    image: "/products/elfbar-ew18k-pod-cotton-candy-ice.jpg",
    inStock: true,
  },
  {
    slug: "elfbar-ew9k-pod-blue-razz",
    name: "EW9K Pod - Blue Razz",
    brand: "Elfbar",
    category: "Disposables",
    price: 180,
    flavour: "Blue Razz",
    image: "/products/elfbar-ew9k-pod-blue-razz.jpg",
    inStock: true,
  },
  {
    slug: "elfbar-ew9k-pod-grape",
    name: "EW9K Pod - Grape",
    brand: "Elfbar",
    category: "Disposables",
    price: 360,
    flavour: "Grape",
    image: "/products/elfbar-ew9k-pod-grape.jpg",
    inStock: true,
  },
  {
    slug: "nasty-dr9ki-blackberry-cranberry-ice",
    name: "DR9Ki - Blackberry Cranberry Ice",
    brand: "Nasty",
    category: "Disposables",
    price: 380,
    flavour: "Blackberry Cranberry Ice",
    image: "/products/nasty-dr9ki-blackberry-cranberry-ice.jpg",
    inStock: true,
  },
  {
    slug: "nasty-dr9ki-cherry-peach-lemon",
    name: "DR9Ki - Cherry Peach Lemon",
    brand: "Nasty",
    category: "Disposables",
    price: 90,
    flavour: "Cherry Peach Lemon",
    image: "/products/nasty-dr9ki-cherry-peach-lemon.jpg",
    inStock: true,
  },
  {
    slug: "nasty-dr9ki-kiwi-passion-fruit-guava",
    name: "DR9Ki - Kiwi Passion Fruit Guava",
    brand: "Nasty",
    category: "Disposables",
    price: 430,
    flavour: "Kiwi Passion Fruit Guava",
    image: "/products/nasty-dr9ki-kiwi-passion-fruit-guava.jpg",
    inStock: true,
  },
  {
    slug: "nasty-dr9ki-lemon-cola",
    name: "DR9Ki - Lemon Cola",
    brand: "Nasty",
    category: "Disposables",
    price: 300,
    compareAt: 380,
    flavour: "Lemon Cola",
    image: "/products/nasty-dr9ki-lemon-cola.jpg",
    inStock: true,
  },
  {
    slug: "nasty-dr9ki-mango",
    name: "DR9Ki - Mango",
    brand: "Nasty",
    category: "Disposables",
    price: 90,
    flavour: "Mango",
    image: "/products/nasty-dr9ki-mango.jpg",
    inStock: true,
  },
  {
    slug: "nasty-dr9ki-tropical-punch-ice",
    name: "DR9Ki - Tropical Punch Ice",
    brand: "Nasty",
    category: "Disposables",
    price: 250,
    flavour: "Tropical Punch Ice",
    image: "/products/nasty-dr9ki-tropical-punch-ice.jpg",
    inStock: true,
  },
  {
    slug: "nasty-surge-55k-blue-chillaz",
    name: "Surge 55K - Blue Chillaz",
    brand: "Nasty",
    category: "Disposables",
    price: 410,
    flavour: "Blueberry Ice",
    image: "/products/nasty-surge-55k-blue-chillaz.jpg",
    inStock: true,
  },
  {
    slug: "nasty-surge-55k-fizzy-cherry",
    name: "Surge 55K - Fizzy Cherry",
    brand: "Nasty",
    category: "Disposables",
    price: 280,
    flavour: "Cherry Cola",
    image: "/products/nasty-surge-55k-fizzy-cherry.jpg",
    inStock: true,
  },
  {
    slug: "nasty-surge-55k-mango-kasi",
    name: "Surge 55K - Mango Kasi",
    brand: "Nasty",
    category: "Disposables",
    price: 210,
    compareAt: 250,
    flavour: "Mango Ice",
    image: "/products/nasty-surge-55k-mango-kasi.jpg",
    inStock: true,
  },
  {
    slug: "nasty-surge-55k-wiks",
    name: "Surge 55K - Wiks",
    brand: "Nasty",
    category: "Disposables",
    price: 420,
    flavour: "Rootbeer Bubblegum",
    image: "/products/nasty-surge-55k-wiks.jpg",
    inStock: true,
  },
  {
    slug: "nasty-volt-30k-cherry-grape-plum",
    name: "Volt 30K - Cherry Grape Plum",
    brand: "Nasty",
    category: "Disposables",
    price: 400,
    compareAt: 470,
    flavour: "Cherry Grape Plum",
    image: "/products/nasty-volt-30k-cherry-grape-plum.jpg",
    inStock: true,
  },
  {
    slug: "nasty-volt-30k-mango-ice",
    name: "Volt 30K - Mango Ice",
    brand: "Nasty",
    category: "Disposables",
    price: 280,
    compareAt: 330,
    flavour: "Mango Ice",
    image: "/products/nasty-volt-30k-mango-ice.jpg",
    inStock: true,
  },
  {
    slug: "nasty-volt-30k-pineapple-passion-fruit-litchi",
    name: "Volt 30K - Pineapple Passion Fruit Litchi",
    brand: "Nasty",
    category: "Disposables",
    price: 140,
    compareAt: 230,
    flavour: "Pineapple Passion Fruit Litchi",
    image: "/products/nasty-volt-30k-pineapple-passion-fruit-litchi.jpg",
    inStock: true,
  },
  {
    slug: "nasty-versa-pod-cherry-grape-plum",
    name: "Versa Pod - Cherry Grape Plum",
    brand: "Nasty",
    category: "Disposables",
    price: 430,
    flavour: "Cherry Grape Plum",
    image: "/products/nasty-versa-pod-cherry-grape-plum.jpg",
    inStock: true,
  },
  {
    slug: "nasty-versa-pod-peach-ice",
    name: "Versa Pod - Peach Ice",
    brand: "Nasty",
    category: "Disposables",
    price: 390,
    flavour: "Peach Ice",
    image: "/products/nasty-versa-pod-peach-ice.jpg",
    inStock: true,
  },
  {
    slug: "nasty-versa-starter-kit-citronnade-twist",
    name: "Versa Starter Kit - Citronnade Twist",
    brand: "Nasty",
    category: "Disposables",
    price: 420,
    flavour: "Citronnade Twist",
    image: "/products/nasty-versa-starter-kit-citronnade-twist.jpg",
    inStock: true,
  },
  {
    slug: "nasty-versa-starter-kit-watermelon-ice",
    name: "Versa Starter Kit - Watermelon Ice",
    brand: "Nasty",
    category: "Disposables",
    price: 220,
    flavour: "Watermelon Ice",
    image: "/products/nasty-versa-starter-kit-watermelon-ice.jpg",
    inStock: true,
  },
  {
    slug: "oxbar-g-prime-25k-cherry-blue-dragonfruit",
    name: "G Prime 25K - Cherry Blue Dragonfruit",
    brand: "Oxbar",
    category: "Disposables",
    price: 210,
    flavour: "Cherry Blue Dragonfruit",
    image: "/products/oxbar-g-prime-25k-cherry-blue-dragonfruit.jpg",
    inStock: true,
  },
  {
    slug: "oxbar-g-prime-25k-mango-slushie",
    name: "G Prime 25K - Mango Slushie",
    brand: "Oxbar",
    category: "Disposables",
    price: 320,
    flavour: "Mango Slushie",
    image: "/products/oxbar-g-prime-25k-mango-slushie.jpg",
    inStock: true,
  },
  {
    slug: "oxbar-g-prime-25k-peach-watermelon",
    name: "G Prime 25K - Peach Watermelon",
    brand: "Oxbar",
    category: "Disposables",
    price: 160,
    compareAt: 190,
    flavour: "Peach Watermelon",
    image: "/products/oxbar-g-prime-25k-peach-watermelon.jpg",
    inStock: true,
  },
  {
    slug: "oxbar-g-turbo-36k-fifty-shades-of-grape",
    name: "G Turbo 36K - Fifty Shades of Grape",
    brand: "Oxbar",
    category: "Disposables",
    price: 440,
    compareAt: 490,
    flavour: "Grape",
    image: "/products/oxbar-g-turbo-36k-fifty-shades-of-grape.jpg",
    inStock: false,
  },
  {
    slug: "oxbar-trifusion-50k-fizzy-cherry",
    name: "Trifusion 50K - Fizzy Cherry",
    brand: "Oxbar",
    category: "Disposables",
    price: 120,
    compareAt: 140,
    flavour: "Fizzy Cherry",
    image: "/products/oxbar-trifusion-50k-fizzy-cherry.jpg",
    inStock: true,
  },
  {
    slug: "oxbar-trifusion-50k-pineapple-coconut",
    name: "Trifusion 50K - Pineapple Coconut",
    brand: "Oxbar",
    category: "Disposables",
    price: 130,
    flavour: "Pineapple Coconut",
    image: "/products/oxbar-trifusion-50k-pineapple-coconut.jpg",
    inStock: true,
  },
  {
    slug: "oxbar-trifusion-50k-watermelon-ice",
    name: "Trifusion 50K - Watermelon Ice",
    brand: "Oxbar",
    category: "Disposables",
    price: 400,
    compareAt: 440,
    flavour: "Watermelon Ice",
    image: "/products/oxbar-trifusion-50k-watermelon-ice.jpg",
    inStock: true,
  },
  {
    slug: "misfits-biscoff-cheesecake-120ml",
    name: "Biscoff Cheesecake 120ml",
    brand: "Misfits",
    category: "E-liquids",
    price: 260,
    flavour: "Biscoff Cheesecake",
    image: "/products/misfits-biscoff-cheesecake-120ml.jpg",
    inStock: true,
  },
  {
    slug: "misfits-butterscotch-custard-120ml",
    name: "Butterscotch Custard 120ml",
    brand: "Misfits",
    category: "E-liquids",
    price: 230,
    flavour: "Butterscotch Custard",
    image: "/products/misfits-butterscotch-custard-120ml.jpg",
    inStock: true,
  },
  {
    slug: "misfits-cereal-milk-120ml",
    name: "Cereal Milk 120ml",
    brand: "Misfits",
    category: "E-liquids",
    price: 110,
    flavour: "Cereal Milk",
    image: "/products/misfits-cereal-milk-120ml.jpg",
    inStock: true,
  },
  {
    slug: "misfits-krispy-treats-120ml",
    name: "Krispy Treats 120ml",
    brand: "Misfits",
    category: "E-liquids",
    price: 210,
    flavour: "Krispy Treats",
    image: "/products/misfits-krispy-treats-120ml.jpg",
    inStock: true,
  },
  {
    slug: "prime-absolute-pineapple-120ml",
    name: "Absolute Pineapple 120ml",
    brand: "PRIME",
    category: "E-liquids",
    price: 290,
    flavour: "Fizzy Pineapple",
    image: "/products/prime-absolute-pineapple-120ml.jpg",
    inStock: true,
  },
  {
    slug: "prime-armageddon-120ml",
    name: "Armageddon 120ml",
    brand: "PRIME",
    category: "E-liquids",
    price: 90,
    flavour: "Strawberry Dessert",
    image: "/products/prime-armageddon-120ml.jpg",
    inStock: true,
  },
  {
    slug: "prime-lemonito-120ml",
    name: "Lemonito 120ml",
    brand: "PRIME",
    category: "E-liquids",
    price: 110,
    compareAt: 160,
    flavour: "Lemon Lime Sherbet",
    image: "/products/prime-lemonito-120ml.jpg",
    inStock: true,
  },
  {
    slug: "prime-mad-cola-120ml",
    name: "Mad Cola 120ml",
    brand: "PRIME",
    category: "E-liquids",
    price: 120,
    flavour: "Fizzy Cola Pop",
    image: "/products/prime-mad-cola-120ml.jpg",
    inStock: true,
  },
  {
    slug: "prime-mango-to-the-max-120ml",
    name: "Mango To The Max 120ml",
    brand: "PRIME",
    category: "E-liquids",
    price: 150,
    flavour: "Mango",
    image: "/products/prime-mango-to-the-max-120ml.jpg",
    inStock: true,
  },
  {
    slug: "prime-wraith-of-the-grapes-120ml",
    name: "Wraith Of The Grapes 120ml",
    brand: "PRIME",
    category: "E-liquids",
    price: 250,
    compareAt: 350,
    flavour: "Sour Grapes",
    image: "/products/prime-wraith-of-the-grapes-120ml.jpg",
    inStock: true,
  },
  {
    slug: "bard-juice-berry-lollipop-30ml",
    name: "Berry Lollipop 30ml",
    brand: "Bard Juice",
    category: "E-liquids",
    price: 100,
    flavour: "Berry Lollipop",
    image: "/products/bard-juice-berry-lollipop-30ml.jpg",
    inStock: true,
  },
  {
    slug: "bard-juice-blue-raspberry-lemonade-30ml",
    name: "Blue Raspberry Lemonade 30ml",
    brand: "Bard Juice",
    category: "E-liquids",
    price: 130,
    flavour: "Blue Raspberry Lemonade",
    image: "/products/bard-juice-blue-raspberry-lemonade-30ml.jpg",
    inStock: true,
  },
  {
    slug: "bard-juice-fresh-mint-30ml",
    name: "Fresh Mint 30ml",
    brand: "Bard Juice",
    category: "E-liquids",
    price: 200,
    flavour: "Fresh Mint",
    image: "/products/bard-juice-fresh-mint-30ml.jpg",
    inStock: true,
  },
  {
    slug: "bard-juice-triple-mango-ice-30ml",
    name: "Triple Mango Ice 30ml",
    brand: "Bard Juice",
    category: "E-liquids",
    price: 80,
    flavour: "Triple Mango Ice",
    image: "/products/bard-juice-triple-mango-ice-30ml.jpg",
    inStock: true,
  },
  {
    slug: "misfits-apricot-jam-swiss-roll-60ml",
    name: "Apricot Jam Swiss Roll 60ml",
    brand: "Misfits",
    category: "E-liquids",
    price: 220,
    flavour: "Apricot Jam Swiss Roll",
    image: "/products/misfits-apricot-jam-swiss-roll-60ml.jpg",
    inStock: true,
  },
  {
    slug: "misfits-malva-pudding-60ml",
    name: "Malva Pudding 60ml",
    brand: "Misfits",
    category: "E-liquids",
    price: 310,
    flavour: "Malva Pudding",
    image: "/products/misfits-malva-pudding-60ml.jpg",
    inStock: true,
  },
  {
    slug: "pukka-juice-blaze-bull-60ml",
    name: "Blaze Bull 60ml",
    brand: "Pukka Juice",
    category: "E-liquids",
    price: 300,
    flavour: "Blaze Bull",
    image: "/products/pukka-juice-blaze-bull-60ml.jpg",
    inStock: true,
  },
  {
    slug: "pukka-juice-cherry-blaze-60ml",
    name: "Cherry Blaze 60ml",
    brand: "Pukka Juice",
    category: "E-liquids",
    price: 140,
    flavour: "Cherry Blaze",
    image: "/products/pukka-juice-cherry-blaze-60ml.jpg",
    inStock: true,
  },
  {
    slug: "pukka-juice-raspberry-sherbet-60ml",
    name: "Raspberry Sherbet 60ml",
    brand: "Pukka Juice",
    category: "E-liquids",
    price: 250,
    compareAt: 320,
    flavour: "Raspberry Sherbet",
    image: "/products/pukka-juice-raspberry-sherbet-60ml.jpg",
    inStock: true,
  },
  {
    slug: "yeti-apricot-watermelon-ice-30ml",
    name: "Apricot Watermelon Ice 30ml",
    brand: "Yeti",
    category: "E-liquids",
    price: 260,
    flavour: "Apricot Watermelon Ice",
    image: "/products/yeti-apricot-watermelon-ice-30ml.jpg",
    inStock: true,
  },
  {
    slug: "yeti-cactus-ice-30ml",
    name: "Cactus Ice 30ml",
    brand: "Yeti",
    category: "E-liquids",
    price: 240,
    compareAt: 340,
    flavour: "Cactus Ice",
    image: "/products/yeti-cactus-ice-30ml.jpg",
    inStock: true,
  },
  {
    slug: "yeti-sour-raspberry-watermelon-ice-30ml",
    name: "Sour Raspberry Watermelon Ice 30ml",
    brand: "Yeti",
    category: "E-liquids",
    price: 130,
    compareAt: 160,
    flavour: "Raspberry Watermelon",
    image: "/products/yeti-sour-raspberry-watermelon-ice-30ml.jpg",
    inStock: true,
  },
  {
    slug: "yeti-mango-ice-50mg-30ml",
    name: "Mango Ice 50mg 30ml",
    brand: "Yeti",
    category: "E-liquids",
    price: 150,
    flavour: "Mango Ice",
    image: "/products/yeti-mango-ice-50mg-30ml.jpg",
    inStock: true,
  },
  {
    slug: "yeti-strawberry-cherry-raspberry-ice-50mg",
    name: "Strawberry Cherry Raspberry Ice 50mg",
    brand: "Yeti",
    category: "E-liquids",
    price: 260,
    compareAt: 280,
    flavour: "Mixed Berry",
    image: "/products/yeti-strawberry-cherry-raspberry-ice-50mg.jpg",
    inStock: true,
  },
  {
    slug: "oxbar-g-turbo-36k-triple-mango-temptation",
    name: "G Turbo 36K - Triple Mango Temptation",
    brand: "Oxbar",
    category: "Disposables",
    price: 350,
    flavour: "Triple Mango",
    image: "/products/oxbar-g-turbo-36k-triple-mango-temptation.jpg",
    inStock: true,
  },
];

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function formatRand(value: number) {
  return `R${value.toLocaleString("en-ZA", { minimumFractionDigits: 2 })}`;
}